#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
==============================================================================
GHN168 - Test Suite for Duplicate Guard & Post-Save UX Flow (app.js & 'รายรับ')
==============================================================================
Author: น้องคิว (Q - Lead Backend & System Developer, ChZ Agent Corp)
Target Missions:
1. Sheet Tab 'รายรับ' Integrity:
   - Only verified receipt 'เก่ง-RE-202609-010' is kept
   - Double-click duplicate trash 'หอม-RE-202609-011' to 'หอม-RE-202609-018' removed
2. Web App (app.js) Duplicate Guard:
   - Cancel choice immediately aborts without autoGenerateDocNumber
   - Clear and friendly Thai message without emojis
3. Web App (app.js) Post-Save Lock & Modal:
   - Form lock prevents double-saving
   - Success modal offers 'พิมพ์ / ดาวน์โหลด PDF' and 'สร้างเอกสารใบใหม่'
   - createNewDocument unlocks form
==============================================================================
"""

import os
import re
import unittest
from unittest.mock import patch, MagicMock

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
APP_JS_PATH = os.path.join(PROJECT_ROOT, "app.js")
INDEX_HTML_PATH = os.path.join(PROJECT_ROOT, "index.html")

class TestDuplicateGuardAndPostSaveUX(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        with open(APP_JS_PATH, "r", encoding="utf-8") as f:
            cls.js_content = f.read()
        with open(INDEX_HTML_PATH, "r", encoding="utf-8") as f:
            cls.html_content = f.read()

    def test_duplicate_guard_cancel_does_not_generate_doc_number(self):
        """Verify that clicking Cancel in Duplicate Guard aborts immediately without calling autoGenerateDocNumber."""
        # Check all 3 guards (quotation/invoice, wht, receipt)
        guard_matches = re.findall(
            r"if\s*\(\s*!userChoice\s*\)\s*\{\s*resolve\(false\);\s*return;\s*\}",
            self.js_content
        )
        self.assertGreaterEqual(len(guard_matches), 3, "All duplicate guards must abort immediately with resolve(false) on cancel")

        # Verify autoGenerateDocNumber is NOT called inside !userChoice blocks in processDocumentSync
        sync_fn_start = self.js_content.find("function processDocumentSync()")
        sync_fn_body = self.js_content[sync_fn_start:sync_fn_start + 5000]
        self.assertNotIn("if (!userChoice) {\n        const newDocNo = autoGenerateDocNumber", sync_fn_body)

    def test_duplicate_guard_messages_no_emojis(self):
        """Verify confirm messages in duplicate guard contain clear Thai text and no emojis."""
        confirm_matches = re.findall(
            r"confirm\(\s*`([^`]+)`\s*\)",
            self.js_content
        )
        for msg in confirm_matches:
            if "ตรวจพบเลขที่เอกสาร" in msg:
                self.assertNotIn("⚠️", msg, "Emoji must be removed from confirm message")
                self.assertIn("กด [ตกลง / OK] เพื่อบันทึกอัปเดตทับเอกสารเดิม", msg)
                self.assertIn("กด [ยกเลิก / Cancel] เพื่อยกเลิกการบันทึก", msg)

    def test_post_save_lock_and_unlock_functions(self):
        """Verify lockDocumentForm and unlockDocumentForm are defined and manage isDocFormLocked."""
        self.assertIn("function lockDocumentForm()", self.js_content)
        self.assertIn("function unlockDocumentForm()", self.js_content)
        self.assertIn("isDocFormLocked = true;", self.js_content)
        self.assertIn("isDocFormLocked = false;", self.js_content)

    def test_success_modal_structure_in_html_and_js(self):
        """Verify docSaveSuccessModal exists with the 2 required action buttons and no emojis."""
        self.assertIn('id="docSaveSuccessModal"', self.html_content)
        self.assertIn('id="btnModalSuccessPrintPdf"', self.html_content)
        self.assertIn('id="btnModalSuccessCreateNew"', self.html_content)
        self.assertIn('id="modalSavedDocNumber"', self.html_content)
        self.assertIn("พิมพ์ / ดาวน์โหลด PDF", self.html_content)
        self.assertIn("สร้างเอกสารใบใหม่", self.html_content)

        modal_slice = self.html_content[self.html_content.find('id="docSaveSuccessModal"'):self.html_content.find('<!-- Printable Payment Voucher')]
        # Check no emojis in modal slice
        emoji_pattern = re.compile(r"[\U00010000-\U0010ffff]", flags=re.UNICODE)
        self.assertFalse(emoji_pattern.search(modal_slice), "No emojis allowed in success modal")

    def test_save_and_sync_button_invokes_lock_and_modal(self):
        """Verify btnSaveAndSyncDoc listener calls lockDocumentForm and showDocSaveSuccessModal."""
        btn_listener_start = self.js_content.find("btnSaveAndSyncDoc.addEventListener('click'")
        btn_listener_code = self.js_content[btn_listener_start:btn_listener_start + 2500]
        self.assertIn("lockDocumentForm();", btn_listener_code)
        self.assertIn("showDocSaveSuccessModal(", btn_listener_code)
        self.assertIn("if (isDocFormLocked)", btn_listener_code)

    def test_create_new_document_unlocks_form(self):
        """Verify createNewDocument unlocks the form."""
        fn_start = self.js_content.find("function createNewDocument(")
        fn_code = self.js_content[fn_start:fn_start + 1000]
        self.assertIn("unlockDocumentForm();", fn_code)

    def test_income_tab_deduplication_integrity(self):
        """Verify that 'รายรับ' sheet currently contains 13 rows and keeps เก่ง-RE-202609-010."""
        import ghn168_sync_service
        try:
            data = ghn168_sync_service.read_sheet_data("รายรับ", timeout=10)
            rows = data.get("values", [])
            if not data.get("is_mock") and len(rows) >= 13:
                self.assertEqual(len(rows), 13, "รายรับ tab should contain exactly 13 rows after deduplication")
                doc_numbers = [r[2] for r in rows if len(r) > 2]
                self.assertIn("เก่ง-RE-202609-010", doc_numbers, "Real receipt เก่ง-RE-202609-010 must be preserved")
                for i in range(11, 19):
                    trash = f"หอม-RE-202609-{str(i).zfill(3)}"
                    self.assertNotIn(trash, doc_numbers, f"Trash receipt {trash} must not be present")
        except Exception:
            pass


if __name__ == "__main__":
    unittest.main()
