import os
import sys

def compile_source_vault(topic, findings, links):
    """
    Skill: Source Vault Compiler
    Purpose: Compiles research links and insights into a format optimized for NotebookLM.
    """
    filename = f"workspace/1_raw_materials/sources_for_notebooklm_{topic.replace(' ', '_')}.md"
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write(f"# 📚 Source Vault for NotebookLM: {topic}\n\n")
        f.write(f"**Project:** WTJ Story\n")
        f.write(f"**Status:** Ready for Upload\n\n")
        f.write(f"--- \n\n")
        f.write(f"## 🔗 Research Links (Copy-Paste to NotebookLM 'Add Website')\n")
        for link in links:
            f.write(f"- {link}\n")
        
        f.write(f"\n## 🧠 Key Insights & Raw Data (For Analysis)\n")
        f.write(findings)
        
        f.write(f"\n\n--- \n*Generated by Antigravity Team Agent System*")
    
    print(f"✅ สร้างไฟล์เสบียงข้อมูลสำหรับ NotebookLM เรียบร้อย: {filename}")

if __name__ == "__main__":
    # ตัวอย่างการใช้งานจริงสำหรับ Game Balancer
    topic = "Game Balancer"
    links = [
        "https://www.glassdoor.com/Salaries/game-balancer-salary-SRCH_KO0,13.htm",
        "https://www.reddit.com/r/GameDesign/comments/game_balancer_pain_points/",
        "https://www.gamedeveloper.com/design/the-art-of-game-balancing",
        "https://en.wikipedia.org/wiki/Game_balancing"
    ]
    findings = """
    - รายได้เฉลี่ย (2026): Junior ฿30k-55k / Mid ฿50k-90k / Senior ฿85k-140k+
    - Pain Points: ความขัดแย้งระหว่าง Data กับ Sentiment ของผู้เล่น, การถูก Doxxing จากแฟนเกมที่โกรธแค้น (โดนเนิร์ฟตัวละคร), วงจรการทำงานที่ไม่มีวันสิ้นสุด (Live Ops)
    - Insight พิเศษ: บางครั้งการแก้ที่ 'ความรู้สึก' (เสียง, กราฟิก) ได้ผลดีกว่าแก้ที่ 'ตัวเลข' (Math)
    """
    compile_source_vault(topic, findings, links)
